Gr 1419 dashi median to mean insert size
oicr-gsi/dashi pull request #358
Opened 2022-06-29 22:17 UTC by mengjenn

Jira ticket or GitHub issue: [GR-1419] Switch Dashi Median Insert Size graphs to Mean Insert Size

- [ ] Updates CHANGELOG.md
- [ ] Updates dev docs if applicable

2022-06-30 13:52 UTC, avarsava commented on application/dash_application/views/call_ready_tar.py
> +        "Mean Insert Size + Intron",
This appears to be the only report where the 'Base Pairs' y-axis label changed, is this correct?

2022-06-30 13:52 UTC, avarsava commented on application/dash_application/views/single_lane_tar.py
> +        "Mean Insert Size with 10/90 Percentile",
This report sems to have a mix of the '+ Intron' and percentile labeling?

2022-06-30 14:18 UTC, slazicoicr requested changes
I get a exception when I open the Single-Lane cfMeDIP view
```
line 254, in generate_mean_insert_size
    bar_positive=INSERT_COL.InsertMean90Percentile,
AttributeError: type object 'InsertSizeMetricsColumn' has no attribute 'InsertMean90Percentile'
```

2022-06-30 14:18 UTC, slazicoicr commented on application/dash_application/utility/plot_builder.py
> +    BAMQC_COL.Insert10Percentile: '10 Percentile Mean Insert: ',
The percentile bars should be removed. QM-024 does not mention distribution information (percentile, standard deviation). I didn't write this in the original ticket, so oversight on my part.

2022-06-30 14:18 UTC, slazicoicr commented on application/dash_application/views/call_ready_tar.py
> +cutoff_insert_mean_label = "Insert Size Mean + Intron"
Introns affect the insert size of RNA (single lane and call ready) only. Targeted sequencing and whole genome views are "Insert Size Mean".

2022-06-30 14:18 UTC, slazicoicr commented on application/dash_application/views/call_ready_wgs.py
> +cutoff_insert_mean_label = "Insert Size Mean + Intron"
Introns are not a concern with whole genome sequencing.

2022-06-30 17:14 UTC, avarsava commented
> 

also getting this, even with the latest changes

2022-06-30 17:21 UTC, mengjenn commented
> > I get a exception when I open the Single-Lane cfMeDIP view
> > ```
> > line 254, in generate_mean_insert_size
> >     bar_positive=INSERT_COL.InsertMean90Percentile,
> > AttributeError: type object 'InsertSizeMetricsColumn' has no attribute 'InsertMean90Percentile'
> > ```
> 
> also getting this, even with the latest changes

Gah, it's the line above calling InsertMean90Percentile (which doesn't exist anymore). Removing it _should_ fix the issue.

2022-06-30 18:15 UTC, slazicoicr requested changes

2022-06-30 18:15 UTC, slazicoicr commented on application/dash_application/views/call_ready_tar.py
> +initial["cutoff_insert_mean"] = 100
Cutoff stays at 150.

2022-06-30 18:15 UTC, slazicoicr commented on application/dash_application/views/single_lane_cfmedip.py
> +        bar_negative=INSERT_COL.InsertMean10Percentile,
For consistency, these bars can go as well.

2022-06-30 18:52 UTC, avarsava approved these changes

2022-07-04 15:02 UTC, slazicoicr approved these changes

2022-07-04 15:40 UTC, merged